spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/yufutas
    username: developer
    password: developer
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
